### ISSUE TITLE
B06 - Kde mininal - Fails to complete the install and more..

### ISSUE THREAD

**Issue by DarkevilPT** [kwankiu/archlinux-installer#47]
Before asking to reboot the system it says 7ji.db failed to download.

kde full worked

**Comment by DarkevilPT** [comment]
![Screenshot_20240502_182254](https://github.com/kwankiu/archlinux-installer/assets/3583885/8779c333-5f97-4c4a-90de-f76d2ee0b307)
acu fails to update wierdly

**Comment by DarkevilPT** [comment]
![20240505_180141](https://github.com/kwankiu/archlinux-installer/assets/3583885/98d7c35e-1d3c-474c-8bef-76be65c3da3a)

![20240505_180219](https://github.com/kwankiu/archlinux-installer/assets/3583885/62d97fe0-b6f7-4186-ad43-eec415a2a08f)


This is gnome minimal 6.1 kernek on b06... Bricked.

**Comment by DarkevilPT** [comment]
Also Kernel 6.1

Get Edge 2 Fan to work:
sudo pacman -S i2c-tools
sudo i2cset -y -f 2 0x18 0x8a 0x18

Doesnt work because the fan is set to work by the kernel but the instructions are bad so if u trigger this it will try to mess with the fan behaviour instead of changing it.. So its kinda conflictuous..

And without these codes the fan behaviour is shit.
So... idk exactly how this goes on 6.1 vb06.

**Comment by kwankiu** [comment]
> ![20240505_180141](https://private-user-images.githubusercontent.com/3583885/328035030-98d7c35e-1d3c-474c-8bef-76be65c3da3a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MTc0MTEsIm5iZiI6MTcxNzUxNzExMSwicGF0aCI6Ii8zNTgzODg1LzMyODAzNTAzMC05OGQ3YzM1ZS0xZDNjLTQ3NGMtOGJlZi03NmJlNjVjM2RhM2EuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTYwNTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjEzMzJmYzVkOTQyMGZlZDEzMDAwZWZmM2QyNDNkOGJhYmJjY2RjNmQ4Y2YyMzdjMDEzZjg5YTVmMzk3OGU3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.00Uaus-rQcm7emGk0hax4lFN-pBJDcVPBCD5qd6cOPI)
> 
> ![20240505_180219](https://private-user-images.githubusercontent.com/3583885/328035035-62d97fe0-b6f7-4186-ad43-eec415a2a08f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MTc0MTEsIm5iZiI6MTcxNzUxNzExMSwicGF0aCI6Ii8zNTgzODg1LzMyODAzNTAzNS02MmQ5N2ZlMC1iNmY3LTQxODYtYWQ0My1lZWM0MTVhMmEwOGYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTYwNTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWVkNGU2YmRlMzM2NjRiMDhiMTZlMjQ2ZmNiNmEzMjNmYmU3NGYyZmRiMjQ2OGRhZGMzMjlmMDg5M2YxY2FjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nWEuLrpptGqZwuQW8IUh1wdjqx7eIbKOH9c9Vgdbotc)
> 
> This is gnome minimal 6.1 kernek on b06... Bricked.
> 
> Going back in time sudo pacman -S librsvg fixed the bricked icons wallpaper.. however.. this is something that was fixed ages ago.

#workaround for missing icons with b06
