### ISSUE TITLE
b08 - edge 2

### ISSUE THREAD

**Issue by DarkevilPT** [kwankiu/archlinux-installer#62]
![20240903_220437](https://github.com/user-attachments/assets/7995e83c-eefc-4704-b756-62f53f6b3a59)

**Comment by DarkevilPT** [comment]
![20240903_220702](https://github.com/user-attachments/assets/68f94f07-577d-4ae6-990a-6ae1249278e9)

**Comment by DarkevilPT** [comment]
![20240903_221042](https://github.com/user-attachments/assets/9fbc9057-ff79-4dd9-8baa-d2d1b5e8f5d4)

**Comment by kwankiu** [comment]
The server seems overload/down, try again later or change the mirrorlist to a server available in your country.

Or use this to generate a mirrorlist available and optimized for your current internet.
```
# Add the misc repo (from source)
acu rem set misc https://github.com/1usOS/PKGBUILDs --branch=misc

# Install rate-mirrors
acu update && acu install misc/rate-mirrors

# Backup original pacman mirrorlist
sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak

# Update your mirrorlist
rate-mirrors archarm | sudo tee /etc/pacman.d/mirrorlist
```
