### ISSUE TITLE
Greenish screen after unlocking / waking up / un-dimming the screen 

### ISSUE THREAD

**Issue by nrpetonr** [kwankiu/archlinux-installer#66]
As described in title, when setting up screen dimming, screen turn-off and/or session suspend in power management, the unlocking / waking up /un-dimming the screen brings the screen back in greenish making it hardly readable. i have to log out and log in to solve this problem.

OS: Arch Linux ARM aarch64, KDE
Host: Orange Pi 5 Plus
Kernel: 6.1.75-rockchip-g5c43412639fd-dirty
Monitor: AOC Q271PB 2560x1440 set to DPI scaling 120%

**Comment by kwankiu** [comment]
> As described in title, when setting up screen dimming, screen turn-off and/or session suspend in power management, the unlocking / waking up /un-dimming the screen brings the screen back in greenish making it hardly readable. i have to log out and log in to solve this problem.
> 
> OS: Arch Linux ARM aarch64, KDE Host: Orange Pi 5 Plus Kernel: 6.1.75-rockchip-g5c43412639fd-dirty Monitor: AOC Q271PB 2560x1440 set to DPI scaling 120%

that‘s a known issue with rockchip 6.1 kernel, as you mentioned, when it happens logout and login again to workaround this issue, or reconnect the hdmi cable.

try using 5.10 or mainline kernel, or open a ticket at Joshua’s or Armbian‘s linux-rockchip
